version: "3.9"

services:
  db:
    image: postgres
    container_name: english_words-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5434:5432'
    command: "postgres -c 'max_connections=500'"
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  redis:
    image: redis
    container_name: english_words-redis
    command: redis-server
    volumes:
      - 'redis:/data'
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

  sidekiq:
    image: sidekiq
    container_name: english_words-sidekiq
    volumes:
      - '.:/app'
      - '/app/tmp' # don't mount tmp directory
    env_file:
      - .env
    depends_on:
      - 'db'
      - 'redis'
    command: bundle exec sidekiq

  web:
    container_name: english_words-web
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  redis:
  postgres_data: {}
