default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV['RAILS_MAX_THREADS'] { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: 5432

development:
  <<: *default
  username: English_words_trainer_development
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['DB_NAME_DEV'] %>

test:
  <<: *default
  database: English_words_trainer_test
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  <<: *default
  database: <%= ENV['DB_NAME_PROD'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
